sudo: false
language: node_js
node_js:
  - "8"
os:
  - osx
  - linux
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
before_script:
  - npm install
  - npm run vscode:prepublish
script:
  - npm run compile
  - npm run test --silent
